Fix minimap show/hide
longturn/freeciv21 pull request #1103
Opened 2022-07-09 20:31 UTC by lmoureaux

Closes #1096.

I chose not to remove the option (for now), instead implementing a more or less sensible behavior.

2022-07-09 20:45 UTC, pranavtifr requested changes
If you dont lock the interface, it resets the position of the chat widget to the default position. That is jarring, and isnt the expected behaviour. The minimap should hide/show without involving the other widgets.

2022-07-09 21:18 UTC, lmoureaux commented
> If you dont lock the interface, it resets the position of the chat widget to the default position. That is jarring, and isnt the expected behaviour. The minimap should hide/show without involving the other widgets.

Fixed. Yes, I used a `switch` with intentional `[[fallthrough]]` (and the C++17 attribute).

2022-07-10 23:57 UTC, pranavtifr commented
Hmm! MacOS build failed!didn't expect that! 😄

2022-07-11 00:03 UTC, pranavtifr approved these changes

2022-07-11 14:21 UTC, merged