Don't default to huge fonts of HiDpi systems
longturn/freeciv21 pull request #1281
Opened 2022-08-15 02:06 UTC by lmoureaux

We have enabled Qt's transparent handling of HiDpi, and thus the manual scaling
that was done in configure_fonts() was useless. Worse, on HiDpi diplays, it
would choose larger fonts to make the UI bigger, which Qt also does internally.
This resulted in huge fonts on such systems.

Simply delete the scaling code. Use the opportunity to tidy up a bit.

See #1273.

2022-08-15 03:18 UTC, jwrober commented
So this is better. Any way to make the font closer to 12 to 14pt, vs 16? Also I don't think help label has a default. Why is it size 9?

![image](https://user-images.githubusercontent.com/23037938/184570923-61b295d1-178e-49a6-8f22-a3c073f6fac4.png)

What about using more generic OS non-specific font names like `monospace` and `sans serif`. I see them available in Linux and Windows. If we are to ship font files, I suggest the Liberation set from LibreOffice. They are GNU v3 I think.

2022-08-15 03:23 UTC, jwrober requested changes
See comment

2022-08-16 22:40 UTC, jwrober commented
> What about using more generic OS non-specific font names like `monospace` and `sans serif`. I see them available in Linux and Windows.

I stand corrected, these are not in Windows (at least not in a fresh install of Win10) so if we want more control, might want to think about shipping some font files. At least per wikipedia, Liberation fonts are OSS - https://en.wikipedia.org/wiki/Liberation_fonts

2022-08-17 00:38 UTC, lmoureaux commented
I'm not pretending to fix all font issues in this PR, just the super large fonts that appeared in some instances. I consider this a bug fix, even if related to https://github.com/longturn/freeciv21/issues/1273, since the defaults weren't applied correctly. Changing the defaults should be another PR IMHO. To bundle fonts, we'd need to change the Windows and Mac installers, which is an even wider scope.

2022-08-17 14:42 UTC, jwrober approved these changes

2022-08-18 23:05 UTC, merged