Set a baseline palette for all themes except System
longturn/freeciv21 pull request #1287
Opened 2022-08-16 01:20 UTC by lmoureaux

In order to achieve consistency in what is displayed regardless of the system
theme, the system color scheme needs to be overriden. Previously only 3 colors
were changed (and for a single theme), which was causing readbility issues when
the system color scheme didn't match the theme.

Always fill the system QPalette with dark colors for dark themes and light
colors for light themes. Use the Breeze Light and Breeze Dark palettes as
references.

There are still some issues when changing the theme on the fly, much like #762.
It looks fine after restarting the game.

2022-08-16 22:20 UTC, jwrober requested changes
For the most part this is great. I am running into an interesting issue however. If I open a saved game and do a global observe to see the background behind the buttons. On NightStalker to start its a darker color, which is a huge improvement over the white background. However, If it switch to Classic theme and then back to NightStalker the background turns white.

2022-08-17 01:21 UTC, lmoureaux commented
> For the most part this is great. I am running into an interesting issue however. If I open a saved game and do a global observe to see the background behind the buttons. On NightStalker to start its a darker color, which is a huge improvement over the white background. However, If it switch to Classic theme and then back to NightStalker the background turns white.

https://stackoverflow.com/questions/38968743/qt-changing-the-background-color-of-qwidget-using-palette-doesnt-work
Looks like a Qt bug. Could work around it...

2022-08-17 14:53 UTC, jwrober commented
I also get this when picking the system theme:
```
[warning] freeciv21-client (../client/themes.cpp:75) - missing color WindowText
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Button
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Light
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Midlight
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Dark
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Mid
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Text
[warning] freeciv21-client (../client/themes.cpp:75) - missing color BrightText
[warning] freeciv21-client (../client/themes.cpp:75) - missing color ButtonText
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Base
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Window
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Shadow
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Highlight
[warning] freeciv21-client (../client/themes.cpp:75) - missing color HighlightedText
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Link
[warning] freeciv21-client (../client/themes.cpp:75) - missing color LinkVisited
[warning] freeciv21-client (../client/themes.cpp:75) - missing color AlternateBase
[warning] freeciv21-client (../client/themes.cpp:75) - missing color ToolTipBase
[warning] freeciv21-client (../client/themes.cpp:75) - missing color ToolTipText
[warning] freeciv21-client (../client/themes.cpp:75) - missing color PlaceholderText
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Foreground
[warning] freeciv21-client (../client/themes.cpp:75) - missing color Background
```

Which I think makes sense because you purposely didn't adjust system theme.

2022-08-17 19:35 UTC, lmoureaux commented
> Which I think makes sense because you purposely didn't adjust system theme.

It shouldn't try and load the palette for the system theme…

2022-08-17 20:32 UTC, lmoureaux commented
Will want to re-check #756

2022-08-17 21:36 UTC, jwrober commented
I think this breaks #756 
![image](https://user-images.githubusercontent.com/23037938/185247742-d61b7b4a-862d-42af-88ed-6491f40f0509.png)

2022-08-17 22:02 UTC, lmoureaux commented
pfff… let's just disable system on Windows?

2022-08-17 22:06 UTC, jwrober commented
> pfff… let's just disable system on Windows?

I'm personally fine with that. I am not sure how many people use System theme anyway.

2022-08-17 22:15 UTC, lmoureaux commented
`System` is now disabled on Windows

2022-08-19 00:26 UTC, jwrober approved these changes

2022-08-19 00:26 UTC, merged