Docs: Coding Guidelines
longturn/freeciv21 pull request #1331
Opened 2022-08-27 03:42 UTC by lmoureaux

This started as #1321 and ended up being #743.

Sorry for the length, I can split if needed...

2022-08-27 15:20 UTC, jwrober requested changes

2022-08-27 15:20 UTC, jwrober commented on docs/Coding/architecture.rst
> +utilities that don't have an equivalent in Qt or the standard library. Freeciv21 also ships with a couple
with a couple of...

2022-08-27 15:20 UTC, jwrober commented on docs/Coding/architecture.rst
> +The client code is grouped in the :file:`client` folder. The server code is located under :file:`server`,
I would suggest "found" instead of "grouped"

2022-08-27 15:20 UTC, jwrober commented on docs/Coding/architecture.rst
> +All the assets used by client and server are grouped under :file:`data`. This includes among
used by "the" client and server...

2022-08-27 15:20 UTC, jwrober commented on docs/Coding/architecture.rst
> +There are a few additional folders that you'll touch less often. The table below describes the complete
you will

2022-08-27 16:22 UTC, daavko reviewed
Looks great in general, found just a couple small things

2022-08-27 16:22 UTC, daavko commented on docs/Coding/architecture.rst
> +Localization files for languages other than English are located under :file:`translations`.
I'd get rid of "for languages other than English", as we do have en-GB in there

2022-08-27 16:22 UTC, daavko commented on docs/Coding/guidelines.rst
> +You do npt need to add your name to the file, but we recommend that you do so. The same information will be
typo
```suggestion
You do not need to add your name to the file, but we recommend that you do so. The same information will be
```

2022-08-27 16:22 UTC, daavko commented on docs/Coding/guidelines.rst
> +This is equivalent to the ancient ``#ifndef``/``#define``/``#endif`` idiom, but also much less error-prone.
```suggestion
This is equivalent to the ancient ``#ifndef``/``#define``/``#endif`` idiom, but much less error-prone.
```

2022-08-27 16:22 UTC, daavko commented on docs/Coding/guidelines.rst
> +The compiler will generate an arbitrary names for symbols in the anonymous namespace that will not clash with
Should be either "an arbitrary name" or "arbitrary names" without "an"

2022-08-27 16:22 UTC, daavko commented on docs/Coding/guidelines.rst
> +Classes that are more complicated than C-like ``struct`` should not have any public variable. Getters and
```suggestion
Classes that are more complicated than C-like ``struct`` should not have any public variables. Getters and
```

2022-08-27 16:22 UTC, daavko commented on docs/Coding/architecture.rst
> +utilities that don't have an equivalent in Qt or the standard library. Freeciv21 also ships with a couple
```suggestion
utilities that do not have an equivalent in Qt or the standard library. Freeciv21 also ships with a couple
```

2022-08-28 14:57 UTC, jwrober approved these changes

2022-08-28 14:57 UTC, merged