Break out production buy gold and turns as columns in city view
longturn/freeciv21 pull request #1409
Opened 2022-10-06 23:22 UTC by jwrober

Also updated the function headers to match coding guidelines

Closes #1052

2022-10-07 16:22 UTC, lmoureaux requested changes
The code with `bufone` and `buf` looks a bit overcomplicated but I guess it fits the style of the file. We'll refactor if/when we turn this to QString

One last suggestion to avoid breaking the blame. Just apply it and stack merge.

2022-10-07 16:22 UTC, lmoureaux commented on client/cityrepdata.cpp
> +   note that numbers are before letters in the ASCII table).
```suggestion
  The following several functions allow intelligent sorting city report
  fields by column.  This doesn't necessarily do the right thing, but
  it's better than sorting alphabetically.
  The GUI gives us two values to compare (as strings).  We try to split
  them into an array of numeric and string fields, then we compare
  lexicographically.  Two numeric fields are compared in the obvious
  way, two character fields are compared alphabetically.  Arbitrarily, a
  numeric field is sorted before a character field (for "justification"
  note that numbers are before letters in the ASCII table).
```

2022-10-07 16:26 UTC, jwrober commented
> The code with `bufone` and `buf` looks a bit overcomplicated but I guess it fits the style of the file. We'll refactor if/when we turn this to QString
> 
I simply copied the function that gathered both gold and turns and then pasted it. So yea, it does use the same style.  

I'll push another commit to fix that block and we can do a squash merge when the CI completes.

2022-10-09 18:25 UTC, lmoureaux approved these changes

2022-10-09 18:25 UTC, merged