Fix random button ordering in PAGE_LOAD
longturn/freeciv21 pull request #1590
Opened 2022-12-11 17:12 UTC by lmoureaux

Ensure that "Browse..." always has a different role than Ok, otherwise Qt does fancy things.

Closes #1582.

2022-12-12 17:43 UTC, jwrober requested changes
Not quite right yet
![image](https://user-images.githubusercontent.com/23037938/207116143-cfa7181c-660e-4b42-ad2d-8631aa384734.png)
![image](https://user-images.githubusercontent.com/23037938/207116197-b45ca024-d613-49ea-93f0-1c472f9ce61b.png)

2022-12-12 17:47 UTC, lmoureaux commented
W.T.F.

2022-12-12 18:23 UTC, jwrober commented
to recreate (at least on my local)
1. open the game, notice what theme you are on
2. click open save game and notice button layout
3. click cancel to go back to the main start screen
4. click options to change the theme
5. click open save game and notice button layout

2022-12-17 18:55 UTC, jwrober approved these changes
Now its the same on both!

2022-12-17 18:55 UTC, merged