Update message options to use a generic code
longturn/freeciv21 pull request #1779
Opened 2023-01-25 21:41 UTC by jwrober

Instead of hard coded ``E_CITY_AQUEDUCT``

Closes #1740

2023-01-27 23:20 UTC, lmoureaux requested changes
Needs backward compatibility code in `options.cpp:message_options_load`, around line 3562.

2023-01-28 15:42 UTC, jwrober commented
Do I add the old values to the `enum event_type old_events[]`?

2023-01-28 21:06 UTC, lmoureaux commented
> Do I add the old values to the `enum event_type old_events[]`?

I don't think so, this seems to be migration code for 2.1 and earlier.

2023-01-28 23:20 UTC, lmoureaux approved these changes

2023-01-28 23:22 UTC, merged