Always display fuel in turns.
longturn/freeciv21 pull request #1830
Opened 2023-02-22 20:06 UTC by psampathkumar

It is tracked as turns internally and helps shows it as turns, it is highly misleading and confusing to show it as movement points instead.

2023-02-22 21:49 UTC, jwrober commented
I'll let lmoureaux comment on the code. I see some things there that might not meet review based on what I was asked to change for the units view work.

![image](https://user-images.githubusercontent.com/23037938/220766925-fdc43695-aba0-4c94-b294-adb86dde62f8.png)

How about a space after the last numeral before `(` and then no space between the turn numeral and `T`? 

e.g. `MP 7 3/9 (0T)`

2023-02-22 21:50 UTC, jwrober requested changes
see comment

2023-02-22 22:22 UTC, lmoureaux requested changes
Since this PR introduces new locale-dependent strings (`%1T`), they should be marked for translation. The code can also be simplified quite a bit.

2023-02-23 00:42 UTC, psampathkumar commented on common/unit.cpp
>            move_points_text(punit->moves_left, false));
I dont think this is visible anywhere in the current client. I just did here for consistency. It used to be visible on the sidebar of GTK client.

2023-02-23 00:43 UTC, psampathkumar commented on client/hudwidget.cpp
> +         + QStringLiteral(" T)");
I thought about this, but adding a translation for just a single letter felt weird to me. But I will add it.

2023-02-23 23:32 UTC, lmoureaux commented on common/unit.cpp
>            move_points_text(punit->moves_left, false));
Maybe remove it if it's not used, or repurpose the function to unify hudwidget and unitselect?

2023-02-28 23:38 UTC, lmoureaux commented on common/unit.cpp
>            move_points_text(punit->moves_left, false));
Looks like it's shown in the city dialog tooltip

2023-04-23 14:19 UTC, psampathkumar commented
I made it into 2 commits to keep the reviewing easy. But, I suggest squashing the commits together at the end.

2023-04-23 14:25 UTC, lmoureaux approved these changes
Thanks!

2023-04-23 15:07 UTC, jwrober approved these changes

2023-04-23 15:07 UTC, merged