Fix loading unhappy sprites when there is more than one
longturn/freeciv21 pull request #1873
Opened 2023-03-20 22:26 UTC by lmoureaux

We were looking for "upkeep.unhappy1", which is actually "upkeep.unhappy" for
historical reasons. So start by looking for "upkeep.unhappy2". Do the same for
other upkeep sprites.

Closes #1859.

Backport candidate.

2023-03-20 22:34 UTC, jwrober requested changes
I know it would be a bit janky, but I think we need to start with `0/blank`, skip `1` with an `if()` and then continue from `2` onwards. That way we get all the sprites to show appropriate instead of completely skipping the first sprite called altogether.

2023-03-20 22:48 UTC, lmoureaux commented
> I know it would be a bit janky, but I think we need to start with `0/blank`, skip `1` with an `if()` and then continue from `2` onwards. That way we get all the sprites to show appropriate instead of completely skipping the first sprite called altogether.

The sprites to load are `upkeep.unhappy`, `upkeep.unhappy2`, `upkeep.unhappy3`, etc. There is no `upkeep.unhappy0` because no sprite is shown when there is no upkeep. Adding a sprite at 0 would be a new feature... I'm not opposed to it but it would need to be optional (couldn't be part of the loop) and the patch shouldn't be backported.

2023-03-20 22:50 UTC, jwrober commented
Right I agree with you. Not asking for a new `.unhappy0`. Just asking to go from `upkeep.unhappy` to `upkeep.unhappy2` and skip `1`. Right now your loop starts at `upkeep.unhappy.2` and ignores the first entry.

2023-03-20 22:54 UTC, lmoureaux commented
hmm then what you actually want is start at 1 and have a special case for the name

2023-03-25 17:48 UTC, lmoureaux commented
> Just don't think a "fix" should ignore a valid sprite.

Coming back to this... which valid sprite is ignored by the fix?

2023-03-25 19:09 UTC, jwrober commented
Column 0, e.g. the very first one on the left.

2023-04-03 00:29 UTC, lmoureaux commented
This is what the loop would look like:
```cpp
  for (i = 1;; i++) {
    if (i == 1) {
      buffer = QStringLiteral("upkeep.unhappy");
    } else {
      buffer = QStringLiteral("upkeep.unhappy%1").arg(QString::number(i));
    }
    auto sprite = load_sprite(t, buffer);
    if (!sprite) {
      break;
    }
    t->sprites.upkeep.unhappy.push_back(sprite);
  }
  if (t->sprites.upkeep.unhappy.empty()) {
    tileset_error(t, LOG_FATAL, "Missing sprite upkeep.unhappy");
  }
```
It's functionally identical to the current code. Not sure if it's more readable...

2023-04-03 22:02 UTC, jwrober commented
The current code does a `for (i = 2...` instead of a `for (i = 1...` and then adds another to `i` with `QString::number(i + 1));`, which on first pass `i` would be 3. I think what you have above looks much better to me.

2023-04-03 22:08 UTC, lmoureaux commented
Aaah I see it now, I was supidly assuming that the two loops (unhappy and food) were identical, but they're not!

2023-05-08 18:37 UTC, jwrober commented
This code update still skips the graphic for 1 upkeep. Amplio and Hexemplio both show upkeep as a quantity, so skipping the first icon won't be accurate.

2023-05-08 19:38 UTC, lmoureaux commented
I have to admit it's a bit weird, but there is no `upkeep.something1`:
https://github.com/longturn/freeciv21/blob/8da632265df6a3c8b2b1c51d1f850dc5c0d0da93/data/amplio2/upkeep.spec#L27-L36

2023-05-08 19:45 UTC, jwrober commented
Agree dealing with the legacy tileset code is a pain. What about using the code you put in an earlier comment to account for the lack of a `1` for `upkeep`? I think that would be better than simply skipping it altogether.

2023-05-08 19:59 UTC, lmoureaux commented
I don't skip it, the special case for the first sprite is handled above the loop as it was before (I didn't touch that part of the code). Or is it just a stylistic preference?

2023-05-08 20:46 UTC, jwrober approved these changes
Ok, with some help from friends I better understand what is going on here. Approved.

2023-05-08 20:47 UTC, merged