Don't wait forever when trying to connect
longturn/freeciv21 pull request #1967
Opened 2023-05-28 01:19 UTC by lmoureaux

This is one of the failure modes of bad connections. Fail to connect after 30s (Qt default). Related to #450.

2023-05-28 01:59 UTC, jwrober requested changes
30s is a very long time to wait with no feedback. Can we add a counter or something to the very bottom of the dialog with a connection counter/countdown? Some visual indicator that the client is trying to connect.

2023-05-28 11:14 UTC, lmoureaux commented
This would require going async (#1050), but refactoring the connection code wouldn't be easy.
Could also reduce the timeout.

2023-05-29 19:45 UTC, jwrober commented
How about we reduce to 15s?

2023-06-12 22:31 UTC, lmoureaux commented
Finally came back to this and decided that 10s should be enough for everyone.

2023-06-13 13:56 UTC, jwrober approved these changes

2023-06-17 15:57 UTC, merged