Add an Add Ons button to start screen that loads mp installer
longturn/freeciv21 pull request #2143
Opened 2024-01-07 16:34 UTC by jwrober

Draft... Still need to figure out how to center mp installer when it launches.

Closes #1366

Part of #2136

2024-01-08 01:07 UTC, lmoureaux requested changes
On Windows the modpack installer is optional. Should we make it mandatory?

2024-01-08 01:07 UTC, lmoureaux commented on client/fc_client.cpp
> +  modProcess->waitForFinished();
We probably don't want to freeze the main window until the installer is closed, potentially triggering dead app dialogs from the system

2024-01-08 22:36 UTC, jwrober commented
> On Windows the modpack installer is optional. Should we make it mandatory?

Just noticed this. Yes I think it has to be now. I'll push another change.

2024-01-08 22:42 UTC, jwrober commented
Turns out the GUI modpack, isn't optional - https://github.com/longturn/freeciv21/blob/master/tools/fcmp/CMakeLists.txt#L34 - the CLI version is so we are good.

2024-01-09 15:16 UTC, lmoureaux approved these changes
We may want to rebrand the installer item as "developer tools" or so then

2024-01-09 15:19 UTC, merged