Refactor encodings
longturn/freeciv21 pull request #2145
Opened 2024-01-08 02:13 UTC by lmoureaux

This PR tries to sanitize the handling of character encodings:
* Remove support for non-utf-8 internal and data encodings.
* Remove all calls to the C file API and replace them with native Qt APIs. This should prevent path encoding issues like #565.

### Checks

I checked the following under `wine` for files with accents in the name:

* Reading serv files (from the server prompt, with the `-r` option, and from the client)
* Finding tilespec file
* Handling UTF-8 ruleset files (Royale's Ħal Saflieni Hypogeum)

I couldn't check the following because the file names don't have accents in my setup:

* Removing the test file used for cmdlevel hack
* Finding and using the client settings file and modpack DB

2025-03-23 22:54 UTC, jwrober requested changes
Looks good to me. Made some suggestions I think we need to iterate on.

2025-03-23 22:54 UTC, jwrober commented on client/connectdlg_common.cpp
> +#include <qglobal.h>
I'd recommend `#include <QtGlobal>` instead.

2025-03-23 22:54 UTC, jwrober commented on utility/fciconv.h
> -#define FC_DEFAULT_DATA_ENCODING "UTF-8"
Why get rid of this? I think we should use global variables like this instead of hard coding in many places. If something is set in one place, that's one thing. But this is set in more than one spot.

2025-03-23 22:54 UTC, jwrober commented on client/client_main.cpp
> +  bind_textdomain_codeset("freeciv21-nations", "UTF-8");
use "FC_DEFAULT_DATA_ENCODING" instead of "UTF-8"

2025-03-23 22:54 UTC, jwrober commented on server/srv_main.cpp
> +  bind_textdomain_codeset("freeciv21-nations", "UTF-8");
use "FC_DEFAULT_DATA_ENCODING" instead of "UTF-8"

2025-03-23 22:54 UTC, jwrober commented on tools/ruledit/ruledit.cpp
> +  bind_textdomain_codeset("freeciv21-ruledit", "UTF-8");
use "FC_DEFAULT_DATA_ENCODING" instead of "UTF-8"

2025-03-23 22:54 UTC, jwrober commented on utility/fciconv.cpp
> +  bind_textdomain_codeset("freeciv21-core", "UTF-8");
use "FC_DEFAULT_DATA_ENCODING" instead of "UTF-8"

2025-03-23 23:42 UTC, lmoureaux commented on utility/fciconv.h
> -#define FC_DEFAULT_DATA_ENCODING "UTF-8"
I elected to remove duplication instead and merged all `bind_textdomain_codeset` calls into a single location. The use of UTF-8 is baked pretty much all over the place (`QString::fromUtf8`, `qUtf8Printable`) so I don't think one more is a problem.

2025-03-24 00:08 UTC, jwrober approved these changes

2025-03-24 00:08 UTC, merged