Update workflows
longturn/freeciv21 pull request #2268
Opened 2024-04-05 22:47 UTC by jwrober

Closes #1922

2024-04-08 21:36 UTC, jwrober commented
Two passes of release on my fork seem to work, however I don't think that this is 100% ready. @lmoureaux thoughts?

2024-04-08 21:40 UTC, lmoureaux commented
What does the `workflow_run` block do?

2024-04-08 21:48 UTC, jwrober commented
> What does the `workflow_run` block do?

Its supposed to act as a "uses" so release should wait on build. That doesn't seem to do anything. I'm leaning to the change in checkout

2024-04-09 23:19 UTC, lmoureaux requested changes

2024-04-09 23:19 UTC, lmoureaux commented on .github/workflows/release.yaml
> +      - completed
Let's remove it if it doesn't work
```suggestion
```

2024-04-17 20:36 UTC, lmoureaux approved these changes

2024-04-17 20:36 UTC, merged