Fix the units report when there are many units
longturn/freeciv21 pull request #2318
Opened 2024-07-07 19:43 UTC by lmoureaux

Split the window horizontally instead of vertically, which facilitates scrolling.

Closes #2313.

2024-07-08 19:36 UTC, blabber commented
Works as intended, but the layout is a little inconsistent now:
![before](https://github.com/longturn/freeciv21/assets/1199257/2deb5942-309e-4d93-aab9-d36347c26eae)

I have hacked this together on `view_units.ui`:
![after](https://github.com/longturn/freeciv21/assets/1199257/429b431e-7dd5-4923-91d5-d7ccdd4df2a4)
 
What do you think?

2024-07-08 19:46 UTC, lmoureaux commented
I agree that your proposed layout looks better. Does it look ok when no units are waiting?

2024-07-08 20:03 UTC, blabber commented
The "units waiting" group is hidden in this case. Feel free to test my proposal (which is a good idea anyways): 38f5dea108bf696f7d0075fb00e84991ae4d8f09

2024-07-17 13:22 UTC, jwrober requested changes
see note above

2024-07-17 13:39 UTC, jwrober commented
Another alternative idea is to change the view to a tabbed interface with units table on one tab and units waiting on a second. Then each table can use the whole screen.

2024-07-18 11:35 UTC, lmoureaux commented
A resizeable split screen can be done with a `QSplitter`. Closing this PR as the required changes go in a vastly different direction.

2024-07-18 11:35 UTC, closed without merging