Fixed fix about fixing mem leak in page load
longturn/freeciv21 pull request #353
Opened 2021-03-21 13:11 UTC by mir3x

Fixed #349

2021-03-21 18:07 UTC, lmoureaux requested changes
Nice finding!

2021-03-21 18:07 UTC, lmoureaux commented on client/gui-qt/page_load.cpp
>                fc_assert_ret(iptr != nullptr);
Should be `fc_assert_ret(!iptr);`

2021-03-21 18:55 UTC, mir3x commented on client/gui-qt/page_load.cpp
>                fc_assert_ret(iptr != nullptr);
fixed

2021-03-22 14:36 UTC, lmoureaux approved these changes

2021-03-22 14:37 UTC, merged