Fix loading WWI scenario
longturn/freeciv21 pull request #748
Opened 2021-11-21 23:44 UTC by lmoureaux

Collection of patches related to Freeciv(.org)'s new AI types "threaded" and "tex" that are not supported in fc21. Basically we always fall back to the classic AI, and only mention "classic" in our scenarios.

Closes #746.

2021-11-21 23:53 UTC, jwrober commented
Is this problem in any of the other built-in scenarios that should be fixed now as well?

2021-11-21 23:54 UTC, lmoureaux commented
> Is this problem in any of the other built-in scenarios that should be fixed now as well?
```
$ grep -r '"tex"' data/scenarios/
$
```
No (and they'd load anyway).

2021-11-23 13:03 UTC, pranavtifr requested changes

2021-11-23 13:03 UTC, pranavtifr commented on common/ai.cpp
> +  auto fb = ai_type_by_name("classic");
log a warning when doing this.

2021-11-28 01:31 UTC, merged